h
khadzhiev909/3course pull request #2
Opened 2023-08-03 16:31 UTC by khadzhiev909

2023-08-07 16:34 UTC, isavinov requested changes

2023-08-07 16:34 UTC, isavinov commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    public ResponseEntity<Faculty> findFacultiesByStudent(@RequestParam Student student) {
Для чего студент целиком в параметре? Передавай id студента, вытаскивай студента из базы, а уже из свойств студента бери его факультет (тогда и методы в репозитории будут не нужны)

2023-08-07 16:34 UTC, isavinov commented on src/main/java/ru/hogwarts/school/controller/StudentController.java
> +    public ResponseEntity<Student> findFacultyByStudent(@RequestParam Faculty faculty) {
Аналогичный комментарий, как и студентам. Передавай id факультета, бери из базы факультет и уже из него список студентов

2023-08-19 16:14 UTC, artem-petrosyan commented on src/main/resources/application.properties
> +
`spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
`
не хватает свойства

2023-08-19 16:14 UTC, artem-petrosyan commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5433/myDB
порт точно 5433?
по умолчанию 5432
если явно не менял порт при установке, пропиши 5432

2023-08-19 16:14 UTC, artem-petrosyan commented on src/main/java/ru/hogwarts/school/repository/AvatarRepository.java
> +    Optional<Avatar> findByStudentAvatar(Long studentId);
Ошибка в названии метода
```suggestion
    Optional<Avatar> findByStudent_Id(Long studentId);
```

2023-08-23 20:33 UTC, artem-petrosyan commented on src/main/java/ru/hogwarts/school/controller/AvatarController.java
> +    }
```suggestion
    public ResponseEntity<Long> upLoadAvatar(@PathVariable Long id, @RequestParam MultipartFile avatar) throws IOException {
        Long avatarId = avatarService.uploadAvatar(id, avatar);
        return ResponseEntity.ok(avatarId);
    }
```
Сделай так, чтобы тело было типа Long

2023-08-23 20:35 UTC, artem-petrosyan commented on src/main/java/ru/hogwarts/school/service/AvatarService.java
> +    void uploadAvatar(Long id, MultipartFile file) throws IOException;
```suggestion
    Long uploadAvatar(Long id, MultipartFile file) throws IOException;
```
Тут тоже поменяй на Long

2023-08-23 20:35 UTC, artem-petrosyan commented on src/main/java/ru/hogwarts/school/service/AvatarServiceImpl.java
> +    public void uploadAvatar(Long id, MultipartFile file) throws IOException {
```suggestion
    public Long uploadAvatar(Long id, MultipartFile file) throws IOException {
```
И тут

2023-08-23 20:35 UTC, artem-petrosyan commented on src/main/java/ru/hogwarts/school/service/AvatarServiceImpl.java
> +    }
```suggestion
        return avatar.getId();
        }
```
В конце верни id

2023-09-01 20:25 UTC, merged